/*
 * Decompiled with CFR 0.2.2 (FabricMC 7c48b8c4).
 */
package net.minecraft.block;

import com.mojang.serialization.MapCodec;
import java.util.function.Function;
import net.minecraft.block.AirBlock;
import net.minecraft.block.AmethystBlock;
import net.minecraft.block.AmethystClusterBlock;
import net.minecraft.block.AnvilBlock;
import net.minecraft.block.AttachedStemBlock;
import net.minecraft.block.AzaleaBlock;
import net.minecraft.block.BambooBlock;
import net.minecraft.block.BambooShootBlock;
import net.minecraft.block.BannerBlock;
import net.minecraft.block.BarrelBlock;
import net.minecraft.block.BarrierBlock;
import net.minecraft.block.BeaconBlock;
import net.minecraft.block.BedBlock;
import net.minecraft.block.BeehiveBlock;
import net.minecraft.block.BeetrootsBlock;
import net.minecraft.block.BellBlock;
import net.minecraft.block.BigDripleafBlock;
import net.minecraft.block.BigDripleafStemBlock;
import net.minecraft.block.BlastFurnaceBlock;
import net.minecraft.block.Block;
import net.minecraft.block.BrewingStandBlock;
import net.minecraft.block.BrushableBlock;
import net.minecraft.block.BubbleColumnBlock;
import net.minecraft.block.BuddingAmethystBlock;
import net.minecraft.block.BulbBlock;
import net.minecraft.block.ButtonBlock;
import net.minecraft.block.CactusBlock;
import net.minecraft.block.CakeBlock;
import net.minecraft.block.CalibratedSculkSensorBlock;
import net.minecraft.block.CampfireBlock;
import net.minecraft.block.CandleBlock;
import net.minecraft.block.CandleCakeBlock;
import net.minecraft.block.CarpetBlock;
import net.minecraft.block.CarrotsBlock;
import net.minecraft.block.CartographyTableBlock;
import net.minecraft.block.CarvedPumpkinBlock;
import net.minecraft.block.CauldronBlock;
import net.minecraft.block.CaveVinesBodyBlock;
import net.minecraft.block.CaveVinesHeadBlock;
import net.minecraft.block.ChainBlock;
import net.minecraft.block.CherryLeavesBlock;
import net.minecraft.block.ChestBlock;
import net.minecraft.block.ChiseledBookshelfBlock;
import net.minecraft.block.ChorusFlowerBlock;
import net.minecraft.block.ChorusPlantBlock;
import net.minecraft.block.CobwebBlock;
import net.minecraft.block.CocoaBlock;
import net.minecraft.block.ColoredFallingBlock;
import net.minecraft.block.CommandBlock;
import net.minecraft.block.ComparatorBlock;
import net.minecraft.block.ComposterBlock;
import net.minecraft.block.ConcretePowderBlock;
import net.minecraft.block.ConduitBlock;
import net.minecraft.block.CoralBlock;
import net.minecraft.block.CoralBlockBlock;
import net.minecraft.block.CoralFanBlock;
import net.minecraft.block.CoralWallFanBlock;
import net.minecraft.block.CrafterBlock;
import net.minecraft.block.CraftingTableBlock;
import net.minecraft.block.CropBlock;
import net.minecraft.block.CryingObsidianBlock;
import net.minecraft.block.DaylightDetectorBlock;
import net.minecraft.block.DeadBushBlock;
import net.minecraft.block.DeadCoralBlock;
import net.minecraft.block.DeadCoralFanBlock;
import net.minecraft.block.DeadCoralWallFanBlock;
import net.minecraft.block.DecoratedPotBlock;
import net.minecraft.block.DetectorRailBlock;
import net.minecraft.block.DirtPathBlock;
import net.minecraft.block.DispenserBlock;
import net.minecraft.block.DoorBlock;
import net.minecraft.block.DragonEggBlock;
import net.minecraft.block.DropperBlock;
import net.minecraft.block.DyedCarpetBlock;
import net.minecraft.block.EnchantingTableBlock;
import net.minecraft.block.EndGatewayBlock;
import net.minecraft.block.EndPortalBlock;
import net.minecraft.block.EndPortalFrameBlock;
import net.minecraft.block.EndRodBlock;
import net.minecraft.block.EnderChestBlock;
import net.minecraft.block.ExperienceDroppingBlock;
import net.minecraft.block.FarmlandBlock;
import net.minecraft.block.FenceBlock;
import net.minecraft.block.FenceGateBlock;
import net.minecraft.block.FireBlock;
import net.minecraft.block.FletchingTableBlock;
import net.minecraft.block.FlowerBlock;
import net.minecraft.block.FlowerPotBlock;
import net.minecraft.block.FlowerbedBlock;
import net.minecraft.block.FluidBlock;
import net.minecraft.block.FrogspawnBlock;
import net.minecraft.block.FrostedIceBlock;
import net.minecraft.block.FungusBlock;
import net.minecraft.block.FurnaceBlock;
import net.minecraft.block.GlazedTerracottaBlock;
import net.minecraft.block.GlowLichenBlock;
import net.minecraft.block.GrassBlock;
import net.minecraft.block.GrateBlock;
import net.minecraft.block.GrindstoneBlock;
import net.minecraft.block.HangingRootsBlock;
import net.minecraft.block.HangingSignBlock;
import net.minecraft.block.HayBlock;
import net.minecraft.block.HeavyCoreBlock;
import net.minecraft.block.HoneyBlock;
import net.minecraft.block.HopperBlock;
import net.minecraft.block.IceBlock;
import net.minecraft.block.InfestedBlock;
import net.minecraft.block.JigsawBlock;
import net.minecraft.block.JukeboxBlock;
import net.minecraft.block.KelpBlock;
import net.minecraft.block.KelpPlantBlock;
import net.minecraft.block.LadderBlock;
import net.minecraft.block.LanternBlock;
import net.minecraft.block.LavaCauldronBlock;
import net.minecraft.block.LeavesBlock;
import net.minecraft.block.LecternBlock;
import net.minecraft.block.LeveledCauldronBlock;
import net.minecraft.block.LeverBlock;
import net.minecraft.block.LightBlock;
import net.minecraft.block.LightningRodBlock;
import net.minecraft.block.LilyPadBlock;
import net.minecraft.block.LoomBlock;
import net.minecraft.block.MagmaBlock;
import net.minecraft.block.MangroveLeavesBlock;
import net.minecraft.block.MangroveRootsBlock;
import net.minecraft.block.MossBlock;
import net.minecraft.block.MudBlock;
import net.minecraft.block.MushroomBlock;
import net.minecraft.block.MushroomPlantBlock;
import net.minecraft.block.MyceliumBlock;
import net.minecraft.block.NetherPortalBlock;
import net.minecraft.block.NetherWartBlock;
import net.minecraft.block.NetherrackBlock;
import net.minecraft.block.NoteBlock;
import net.minecraft.block.NyliumBlock;
import net.minecraft.block.ObserverBlock;
import net.minecraft.block.OxidizableBlock;
import net.minecraft.block.OxidizableBulbBlock;
import net.minecraft.block.OxidizableDoorBlock;
import net.minecraft.block.OxidizableGrateBlock;
import net.minecraft.block.OxidizableSlabBlock;
import net.minecraft.block.OxidizableStairsBlock;
import net.minecraft.block.OxidizableTrapdoorBlock;
import net.minecraft.block.PaneBlock;
import net.minecraft.block.PillarBlock;
import net.minecraft.block.PistonBlock;
import net.minecraft.block.PistonExtensionBlock;
import net.minecraft.block.PistonHeadBlock;
import net.minecraft.block.PitcherCropBlock;
import net.minecraft.block.PlayerSkullBlock;
import net.minecraft.block.PointedDripstoneBlock;
import net.minecraft.block.PotatoesBlock;
import net.minecraft.block.PowderSnowBlock;
import net.minecraft.block.PoweredRailBlock;
import net.minecraft.block.PressurePlateBlock;
import net.minecraft.block.PropaguleBlock;
import net.minecraft.block.PumpkinBlock;
import net.minecraft.block.RailBlock;
import net.minecraft.block.RedstoneBlock;
import net.minecraft.block.RedstoneLampBlock;
import net.minecraft.block.RedstoneOreBlock;
import net.minecraft.block.RedstoneTorchBlock;
import net.minecraft.block.RedstoneWireBlock;
import net.minecraft.block.RepeaterBlock;
import net.minecraft.block.RespawnAnchorBlock;
import net.minecraft.block.RootedDirtBlock;
import net.minecraft.block.RootsBlock;
import net.minecraft.block.RotatedInfestedBlock;
import net.minecraft.block.SaplingBlock;
import net.minecraft.block.ScaffoldingBlock;
import net.minecraft.block.SculkBlock;
import net.minecraft.block.SculkCatalystBlock;
import net.minecraft.block.SculkSensorBlock;
import net.minecraft.block.SculkShriekerBlock;
import net.minecraft.block.SculkVeinBlock;
import net.minecraft.block.SeaPickleBlock;
import net.minecraft.block.SeagrassBlock;
import net.minecraft.block.ShortPlantBlock;
import net.minecraft.block.ShulkerBoxBlock;
import net.minecraft.block.SignBlock;
import net.minecraft.block.SkullBlock;
import net.minecraft.block.SlabBlock;
import net.minecraft.block.SlimeBlock;
import net.minecraft.block.SmallDripleafBlock;
import net.minecraft.block.SmithingTableBlock;
import net.minecraft.block.SmokerBlock;
import net.minecraft.block.SnifferEggBlock;
import net.minecraft.block.SnowBlock;
import net.minecraft.block.SnowyBlock;
import net.minecraft.block.SoulFireBlock;
import net.minecraft.block.SoulSandBlock;
import net.minecraft.block.SpawnerBlock;
import net.minecraft.block.SpongeBlock;
import net.minecraft.block.SporeBlossomBlock;
import net.minecraft.block.SproutsBlock;
import net.minecraft.block.StainedGlassBlock;
import net.minecraft.block.StainedGlassPaneBlock;
import net.minecraft.block.StairsBlock;
import net.minecraft.block.StemBlock;
import net.minecraft.block.StonecutterBlock;
import net.minecraft.block.StructureBlock;
import net.minecraft.block.StructureVoidBlock;
import net.minecraft.block.SugarCaneBlock;
import net.minecraft.block.SweetBerryBushBlock;
import net.minecraft.block.TallFlowerBlock;
import net.minecraft.block.TallPlantBlock;
import net.minecraft.block.TallSeagrassBlock;
import net.minecraft.block.TargetBlock;
import net.minecraft.block.TintedGlassBlock;
import net.minecraft.block.TntBlock;
import net.minecraft.block.TorchBlock;
import net.minecraft.block.TorchflowerBlock;
import net.minecraft.block.TranslucentBlock;
import net.minecraft.block.TransparentBlock;
import net.minecraft.block.TrapdoorBlock;
import net.minecraft.block.TrappedChestBlock;
import net.minecraft.block.TrialSpawnerBlock;
import net.minecraft.block.TripwireBlock;
import net.minecraft.block.TripwireHookBlock;
import net.minecraft.block.TurtleEggBlock;
import net.minecraft.block.TwistingVinesBlock;
import net.minecraft.block.TwistingVinesPlantBlock;
import net.minecraft.block.VaultBlock;
import net.minecraft.block.VineBlock;
import net.minecraft.block.WallBannerBlock;
import net.minecraft.block.WallBlock;
import net.minecraft.block.WallHangingSignBlock;
import net.minecraft.block.WallPiglinHeadBlock;
import net.minecraft.block.WallPlayerSkullBlock;
import net.minecraft.block.WallRedstoneTorchBlock;
import net.minecraft.block.WallSignBlock;
import net.minecraft.block.WallSkullBlock;
import net.minecraft.block.WallTorchBlock;
import net.minecraft.block.WallWitherSkullBlock;
import net.minecraft.block.WearableCarvedPumpkinBlock;
import net.minecraft.block.WeepingVinesBlock;
import net.minecraft.block.WeepingVinesPlantBlock;
import net.minecraft.block.WeightedPressurePlateBlock;
import net.minecraft.block.WetSpongeBlock;
import net.minecraft.block.WitherRoseBlock;
import net.minecraft.block.WitherSkullBlock;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;

public class BlockTypes {
    public static final MapCodec<Block> CODEC = Registries.BLOCK_TYPE.getCodec().dispatchMap(Block::getCodec, Function.identity());

    public static MapCodec<? extends Block> registerAndGetDefault(Registry<MapCodec<? extends Block>> registry) {
        Registry.register(registry, "block", Block.CODEC);
        Registry.register(registry, "air", AirBlock.CODEC);
        Registry.register(registry, "amethyst", AmethystBlock.CODEC);
        Registry.register(registry, "amethyst_cluster", AmethystClusterBlock.CODEC);
        Registry.register(registry, "anvil", AnvilBlock.CODEC);
        Registry.register(registry, "attached_stem", AttachedStemBlock.CODEC);
        Registry.register(registry, "azalea", AzaleaBlock.CODEC);
        Registry.register(registry, "bamboo_sapling", BambooShootBlock.CODEC);
        Registry.register(registry, "bamboo_stalk", BambooBlock.CODEC);
        Registry.register(registry, "banner", BannerBlock.CODEC);
        Registry.register(registry, "barrel", BarrelBlock.CODEC);
        Registry.register(registry, "barrier", BarrierBlock.CODEC);
        Registry.register(registry, "base_coral_fan", DeadCoralFanBlock.CODEC);
        Registry.register(registry, "base_coral_plant", DeadCoralBlock.CODEC);
        Registry.register(registry, "base_coral_wall_fan", DeadCoralWallFanBlock.CODEC);
        Registry.register(registry, "beacon", BeaconBlock.CODEC);
        Registry.register(registry, "bed", BedBlock.CODEC);
        Registry.register(registry, "beehive", BeehiveBlock.CODEC);
        Registry.register(registry, "beetroot", BeetrootsBlock.CODEC);
        Registry.register(registry, "bell", BellBlock.CODEC);
        Registry.register(registry, "big_dripleaf", BigDripleafBlock.CODEC);
        Registry.register(registry, "big_dripleaf_stem", BigDripleafStemBlock.CODEC);
        Registry.register(registry, "blast_furnace", BlastFurnaceBlock.CODEC);
        Registry.register(registry, "brewing_stand", BrewingStandBlock.CODEC);
        Registry.register(registry, "brushable", BrushableBlock.CODEC);
        Registry.register(registry, "bubble_column", BubbleColumnBlock.CODEC);
        Registry.register(registry, "budding_amethyst", BuddingAmethystBlock.CODEC);
        Registry.register(registry, "button", ButtonBlock.CODEC);
        Registry.register(registry, "cactus", CactusBlock.CODEC);
        Registry.register(registry, "cake", CakeBlock.CODEC);
        Registry.register(registry, "calibrated_sculk_sensor", CalibratedSculkSensorBlock.CODEC);
        Registry.register(registry, "campfire", CampfireBlock.CODEC);
        Registry.register(registry, "candle_cake", CandleCakeBlock.CODEC);
        Registry.register(registry, "candle", CandleBlock.CODEC);
        Registry.register(registry, "carpet", CarpetBlock.CODEC);
        Registry.register(registry, "carrot", CarrotsBlock.CODEC);
        Registry.register(registry, "cartography_table", CartographyTableBlock.CODEC);
        Registry.register(registry, "carved_pumpkin", WearableCarvedPumpkinBlock.CODEC);
        Registry.register(registry, "cauldron", CauldronBlock.CODEC);
        Registry.register(registry, "cave_vines", CaveVinesHeadBlock.CODEC);
        Registry.register(registry, "cave_vines_plant", CaveVinesBodyBlock.CODEC);
        Registry.register(registry, "ceiling_hanging_sign", HangingSignBlock.CODEC);
        Registry.register(registry, "chain", ChainBlock.CODEC);
        Registry.register(registry, "cherry_leaves", CherryLeavesBlock.CODEC);
        Registry.register(registry, "chest", ChestBlock.CODEC);
        Registry.register(registry, "chiseled_book_shelf", ChiseledBookshelfBlock.CODEC);
        Registry.register(registry, "chorus_flower", ChorusFlowerBlock.CODEC);
        Registry.register(registry, "chorus_plant", ChorusPlantBlock.CODEC);
        Registry.register(registry, "cocoa", CocoaBlock.CODEC);
        Registry.register(registry, "colored_falling", ColoredFallingBlock.CODEC);
        Registry.register(registry, "command", CommandBlock.CODEC);
        Registry.register(registry, "comparator", ComparatorBlock.CODEC);
        Registry.register(registry, "composter", ComposterBlock.CODEC);
        Registry.register(registry, "concrete_powder", ConcretePowderBlock.CODEC);
        Registry.register(registry, "conduit", ConduitBlock.CODEC);
        Registry.register(registry, "copper_bulb_block", BulbBlock.CODEC);
        Registry.register(registry, "coral", CoralBlockBlock.CODEC);
        Registry.register(registry, "coral_fan", CoralFanBlock.CODEC);
        Registry.register(registry, "coral_plant", CoralBlock.CODEC);
        Registry.register(registry, "coral_wall_fan", CoralWallFanBlock.CODEC);
        Registry.register(registry, "crafter", CrafterBlock.CODEC);
        Registry.register(registry, "crafting_table", CraftingTableBlock.CODEC);
        Registry.register(registry, "crop", CropBlock.CODEC);
        Registry.register(registry, "crying_obsidian", CryingObsidianBlock.CODEC);
        Registry.register(registry, "daylight_detector", DaylightDetectorBlock.CODEC);
        Registry.register(registry, "dead_bush", DeadBushBlock.CODEC);
        Registry.register(registry, "decorated_pot", DecoratedPotBlock.CODEC);
        Registry.register(registry, "detector_rail", DetectorRailBlock.CODEC);
        Registry.register(registry, "dirt_path", DirtPathBlock.CODEC);
        Registry.register(registry, "dispenser", DispenserBlock.CODEC);
        Registry.register(registry, "door", DoorBlock.CODEC);
        Registry.register(registry, "double_plant", TallPlantBlock.CODEC);
        Registry.register(registry, "dragon_egg", DragonEggBlock.CODEC);
        Registry.register(registry, "drop_experience", ExperienceDroppingBlock.CODEC);
        Registry.register(registry, "dropper", DropperBlock.CODEC);
        Registry.register(registry, "enchantment_table", EnchantingTableBlock.CODEC);
        Registry.register(registry, "ender_chest", EnderChestBlock.CODEC);
        Registry.register(registry, "end_gateway", EndGatewayBlock.CODEC);
        Registry.register(registry, "end_portal", EndPortalBlock.CODEC);
        Registry.register(registry, "end_portal_frame", EndPortalFrameBlock.CODEC);
        Registry.register(registry, "end_rod", EndRodBlock.CODEC);
        Registry.register(registry, "farm", FarmlandBlock.CODEC);
        Registry.register(registry, "fence", FenceBlock.CODEC);
        Registry.register(registry, "fence_gate", FenceGateBlock.CODEC);
        Registry.register(registry, "fire", FireBlock.CODEC);
        Registry.register(registry, "fletching_table", FletchingTableBlock.CODEC);
        Registry.register(registry, "flower", FlowerBlock.CODEC);
        Registry.register(registry, "flower_pot", FlowerPotBlock.CODEC);
        Registry.register(registry, "frogspawn", FrogspawnBlock.CODEC);
        Registry.register(registry, "frosted_ice", FrostedIceBlock.CODEC);
        Registry.register(registry, "fungus", FungusBlock.CODEC);
        Registry.register(registry, "furnace", FurnaceBlock.CODEC);
        Registry.register(registry, "glazed_terracotta", GlazedTerracottaBlock.CODEC);
        Registry.register(registry, "glow_lichen", GlowLichenBlock.CODEC);
        Registry.register(registry, "grass", GrassBlock.CODEC);
        Registry.register(registry, "grindstone", GrindstoneBlock.CODEC);
        Registry.register(registry, "half_transparent", TranslucentBlock.CODEC);
        Registry.register(registry, "hanging_roots", HangingRootsBlock.CODEC);
        Registry.register(registry, "hay", HayBlock.CODEC);
        Registry.register(registry, "heavy_core", HeavyCoreBlock.CODEC);
        Registry.register(registry, "honey", HoneyBlock.CODEC);
        Registry.register(registry, "hopper", HopperBlock.CODEC);
        Registry.register(registry, "huge_mushroom", MushroomBlock.CODEC);
        Registry.register(registry, "ice", IceBlock.CODEC);
        Registry.register(registry, "infested", InfestedBlock.CODEC);
        Registry.register(registry, "infested_rotated_pillar", RotatedInfestedBlock.CODEC);
        Registry.register(registry, "iron_bars", PaneBlock.CODEC);
        Registry.register(registry, "jack_o_lantern", CarvedPumpkinBlock.CODEC);
        Registry.register(registry, "jigsaw", JigsawBlock.CODEC);
        Registry.register(registry, "jukebox", JukeboxBlock.CODEC);
        Registry.register(registry, "kelp", KelpBlock.CODEC);
        Registry.register(registry, "kelp_plant", KelpPlantBlock.CODEC);
        Registry.register(registry, "ladder", LadderBlock.CODEC);
        Registry.register(registry, "lantern", LanternBlock.CODEC);
        Registry.register(registry, "lava_cauldron", LavaCauldronBlock.CODEC);
        Registry.register(registry, "layered_cauldron", LeveledCauldronBlock.CODEC);
        Registry.register(registry, "leaves", LeavesBlock.CODEC);
        Registry.register(registry, "lectern", LecternBlock.CODEC);
        Registry.register(registry, "lever", LeverBlock.CODEC);
        Registry.register(registry, "light", LightBlock.CODEC);
        Registry.register(registry, "lightning_rod", LightningRodBlock.CODEC);
        Registry.register(registry, "liquid", FluidBlock.CODEC);
        Registry.register(registry, "loom", LoomBlock.CODEC);
        Registry.register(registry, "magma", MagmaBlock.CODEC);
        Registry.register(registry, "mangrove_leaves", MangroveLeavesBlock.CODEC);
        Registry.register(registry, "mangrove_propagule", PropaguleBlock.CODEC);
        Registry.register(registry, "mangrove_roots", MangroveRootsBlock.CODEC);
        Registry.register(registry, "moss", MossBlock.CODEC);
        Registry.register(registry, "moving_piston", PistonExtensionBlock.CODEC);
        Registry.register(registry, "mud", MudBlock.CODEC);
        Registry.register(registry, "mushroom", MushroomPlantBlock.CODEC);
        Registry.register(registry, "mycelium", MyceliumBlock.CODEC);
        Registry.register(registry, "nether_portal", NetherPortalBlock.CODEC);
        Registry.register(registry, "netherrack", NetherrackBlock.CODEC);
        Registry.register(registry, "nether_sprouts", SproutsBlock.CODEC);
        Registry.register(registry, "nether_wart", NetherWartBlock.CODEC);
        Registry.register(registry, "note", NoteBlock.CODEC);
        Registry.register(registry, "nylium", NyliumBlock.CODEC);
        Registry.register(registry, "observer", ObserverBlock.CODEC);
        Registry.register(registry, "piglinwallskull", WallPiglinHeadBlock.CODEC);
        Registry.register(registry, "pink_petals", FlowerbedBlock.CODEC);
        Registry.register(registry, "piston_base", PistonBlock.CODEC);
        Registry.register(registry, "piston_head", PistonHeadBlock.CODEC);
        Registry.register(registry, "pitcher_crop", PitcherCropBlock.CODEC);
        Registry.register(registry, "player_head", PlayerSkullBlock.CODEC);
        Registry.register(registry, "player_wall_head", WallPlayerSkullBlock.CODEC);
        Registry.register(registry, "pointed_dripstone", PointedDripstoneBlock.CODEC);
        Registry.register(registry, "potato", PotatoesBlock.CODEC);
        Registry.register(registry, "powder_snow", PowderSnowBlock.CODEC);
        Registry.register(registry, "powered", RedstoneBlock.CODEC);
        Registry.register(registry, "powered_rail", PoweredRailBlock.CODEC);
        Registry.register(registry, "pressure_plate", PressurePlateBlock.CODEC);
        Registry.register(registry, "pumpkin", PumpkinBlock.CODEC);
        Registry.register(registry, "rail", RailBlock.CODEC);
        Registry.register(registry, "redstone_lamp", RedstoneLampBlock.CODEC);
        Registry.register(registry, "redstone_ore", RedstoneOreBlock.CODEC);
        Registry.register(registry, "redstone_torch", RedstoneTorchBlock.CODEC);
        Registry.register(registry, "redstone_wall_torch", WallRedstoneTorchBlock.CODEC);
        Registry.register(registry, "redstone_wire", RedstoneWireBlock.CODEC);
        Registry.register(registry, "repeater", RepeaterBlock.CODEC);
        Registry.register(registry, "respawn_anchor", RespawnAnchorBlock.CODEC);
        Registry.register(registry, "rooted_dirt", RootedDirtBlock.CODEC);
        Registry.register(registry, "roots", RootsBlock.CODEC);
        Registry.register(registry, "rotated_pillar", PillarBlock.CODEC);
        Registry.register(registry, "sapling", SaplingBlock.CODEC);
        Registry.register(registry, "scaffolding", ScaffoldingBlock.CODEC);
        Registry.register(registry, "sculk_catalyst", SculkCatalystBlock.CODEC);
        Registry.register(registry, "sculk", SculkBlock.CODEC);
        Registry.register(registry, "sculk_sensor", SculkSensorBlock.CODEC);
        Registry.register(registry, "sculk_shrieker", SculkShriekerBlock.CODEC);
        Registry.register(registry, "sculk_vein", SculkVeinBlock.CODEC);
        Registry.register(registry, "seagrass", SeagrassBlock.CODEC);
        Registry.register(registry, "sea_pickle", SeaPickleBlock.CODEC);
        Registry.register(registry, "shulker_box", ShulkerBoxBlock.CODEC);
        Registry.register(registry, "skull", SkullBlock.CODEC);
        Registry.register(registry, "slab", SlabBlock.CODEC);
        Registry.register(registry, "slime", SlimeBlock.CODEC);
        Registry.register(registry, "small_dripleaf", SmallDripleafBlock.CODEC);
        Registry.register(registry, "smithing_table", SmithingTableBlock.CODEC);
        Registry.register(registry, "smoker", SmokerBlock.CODEC);
        Registry.register(registry, "sniffer_egg", SnifferEggBlock.CODEC);
        Registry.register(registry, "snow_layer", SnowBlock.CODEC);
        Registry.register(registry, "snowy_dirt", SnowyBlock.CODEC);
        Registry.register(registry, "soul_fire", SoulFireBlock.CODEC);
        Registry.register(registry, "soul_sand", SoulSandBlock.CODEC);
        Registry.register(registry, "spawner", SpawnerBlock.CODEC);
        Registry.register(registry, "sponge", SpongeBlock.CODEC);
        Registry.register(registry, "spore_blossom", SporeBlossomBlock.CODEC);
        Registry.register(registry, "stained_glass_pane", StainedGlassPaneBlock.CODEC);
        Registry.register(registry, "stained_glass", StainedGlassBlock.CODEC);
        Registry.register(registry, "stair", StairsBlock.CODEC);
        Registry.register(registry, "standing_sign", SignBlock.CODEC);
        Registry.register(registry, "stem", StemBlock.CODEC);
        Registry.register(registry, "stonecutter", StonecutterBlock.CODEC);
        Registry.register(registry, "structure", StructureBlock.CODEC);
        Registry.register(registry, "structure_void", StructureVoidBlock.CODEC);
        Registry.register(registry, "sugar_cane", SugarCaneBlock.CODEC);
        Registry.register(registry, "sweet_berry_bush", SweetBerryBushBlock.CODEC);
        Registry.register(registry, "tall_flower", TallFlowerBlock.CODEC);
        Registry.register(registry, "tall_grass", ShortPlantBlock.CODEC);
        Registry.register(registry, "tall_seagrass", TallSeagrassBlock.CODEC);
        Registry.register(registry, "target", TargetBlock.CODEC);
        Registry.register(registry, "tinted_glass", TintedGlassBlock.CODEC);
        Registry.register(registry, "tnt", TntBlock.CODEC);
        Registry.register(registry, "torchflower_crop", TorchflowerBlock.CODEC);
        Registry.register(registry, "torch", TorchBlock.CODEC);
        Registry.register(registry, "transparent", TransparentBlock.CODEC);
        Registry.register(registry, "trapdoor", TrapdoorBlock.CODEC);
        Registry.register(registry, "trapped_chest", TrappedChestBlock.CODEC);
        Registry.register(registry, "trial_spawner", TrialSpawnerBlock.CODEC);
        Registry.register(registry, "trip_wire_hook", TripwireHookBlock.CODEC);
        Registry.register(registry, "tripwire", TripwireBlock.CODEC);
        Registry.register(registry, "turtle_egg", TurtleEggBlock.CODEC);
        Registry.register(registry, "twisting_vines_plant", TwistingVinesPlantBlock.CODEC);
        Registry.register(registry, "twisting_vines", TwistingVinesBlock.CODEC);
        Registry.register(registry, "vault", VaultBlock.CODEC);
        Registry.register(registry, "vine", VineBlock.CODEC);
        Registry.register(registry, "wall_banner", WallBannerBlock.CODEC);
        Registry.register(registry, "wall_hanging_sign", WallHangingSignBlock.CODEC);
        Registry.register(registry, "wall_sign", WallSignBlock.CODEC);
        Registry.register(registry, "wall_skull", WallSkullBlock.CODEC);
        Registry.register(registry, "wall_torch", WallTorchBlock.CODEC);
        Registry.register(registry, "wall", WallBlock.CODEC);
        Registry.register(registry, "waterlily", LilyPadBlock.CODEC);
        Registry.register(registry, "waterlogged_transparent", GrateBlock.CODEC);
        Registry.register(registry, "weathering_copper_bulb", OxidizableBulbBlock.CODEC);
        Registry.register(registry, "weathering_copper_door", OxidizableDoorBlock.CODEC);
        Registry.register(registry, "weathering_copper_full", OxidizableBlock.CODEC);
        Registry.register(registry, "weathering_copper_grate", OxidizableGrateBlock.CODEC);
        Registry.register(registry, "weathering_copper_slab", OxidizableSlabBlock.CODEC);
        Registry.register(registry, "weathering_copper_stair", OxidizableStairsBlock.CODEC);
        Registry.register(registry, "weathering_copper_trap_door", OxidizableTrapdoorBlock.CODEC);
        Registry.register(registry, "web", CobwebBlock.CODEC);
        Registry.register(registry, "weeping_vines_plant", WeepingVinesPlantBlock.CODEC);
        Registry.register(registry, "weeping_vines", WeepingVinesBlock.CODEC);
        Registry.register(registry, "weighted_pressure_plate", WeightedPressurePlateBlock.CODEC);
        Registry.register(registry, "wet_sponge", WetSpongeBlock.CODEC);
        Registry.register(registry, "wither_rose", WitherRoseBlock.CODEC);
        Registry.register(registry, "wither_skull", WitherSkullBlock.CODEC);
        Registry.register(registry, "wither_wall_skull", WallWitherSkullBlock.CODEC);
        return Registry.register(registry, "wool_carpet", DyedCarpetBlock.CODEC);
    }
}

