package net.minecraft.registry.tag;

import net.minecraft.registry.RegistryKeys;
import net.minecraft.util.Identifier;

public final class ItemTags {
   public static final TagKey WOOL = of("wool");
   public static final TagKey PLANKS = of("planks");
   public static final TagKey STONE_BRICKS = of("stone_bricks");
   public static final TagKey WOODEN_BUTTONS = of("wooden_buttons");
   public static final TagKey BUTTONS = of("buttons");
   public static final TagKey WOOL_CARPETS = of("wool_carpets");
   public static final TagKey WOODEN_DOORS = of("wooden_doors");
   public static final TagKey WOODEN_STAIRS = of("wooden_stairs");
   public static final TagKey WOODEN_SLABS = of("wooden_slabs");
   public static final TagKey WOODEN_FENCES = of("wooden_fences");
   public static final TagKey FENCE_GATES = of("fence_gates");
   public static final TagKey WOODEN_PRESSURE_PLATES = of("wooden_pressure_plates");
   public static final TagKey WOODEN_TRAPDOORS = of("wooden_trapdoors");
   public static final TagKey DOORS = of("doors");
   public static final TagKey SAPLINGS = of("saplings");
   public static final TagKey LOGS_THAT_BURN = of("logs_that_burn");
   public static final TagKey LOGS = of("logs");
   public static final TagKey DARK_OAK_LOGS = of("dark_oak_logs");
   public static final TagKey OAK_LOGS = of("oak_logs");
   public static final TagKey BIRCH_LOGS = of("birch_logs");
   public static final TagKey ACACIA_LOGS = of("acacia_logs");
   public static final TagKey CHERRY_LOGS = of("cherry_logs");
   public static final TagKey JUNGLE_LOGS = of("jungle_logs");
   public static final TagKey SPRUCE_LOGS = of("spruce_logs");
   public static final TagKey MANGROVE_LOGS = of("mangrove_logs");
   public static final TagKey CRIMSON_STEMS = of("crimson_stems");
   public static final TagKey WARPED_STEMS = of("warped_stems");
   public static final TagKey BAMBOO_BLOCKS = of("bamboo_blocks");
   public static final TagKey WART_BLOCKS = of("wart_blocks");
   public static final TagKey BANNERS = of("banners");
   public static final TagKey SAND = of("sand");
   public static final TagKey SMELTS_TO_GLASS = of("smelts_to_glass");
   public static final TagKey STAIRS = of("stairs");
   public static final TagKey SLABS = of("slabs");
   public static final TagKey WALLS = of("walls");
   public static final TagKey ANVIL = of("anvil");
   public static final TagKey RAILS = of("rails");
   public static final TagKey LEAVES = of("leaves");
   public static final TagKey TRAPDOORS = of("trapdoors");
   public static final TagKey SMALL_FLOWERS = of("small_flowers");
   public static final TagKey BEDS = of("beds");
   public static final TagKey FENCES = of("fences");
   public static final TagKey TALL_FLOWERS = of("tall_flowers");
   public static final TagKey FLOWERS = of("flowers");
   public static final TagKey PIGLIN_REPELLENTS = of("piglin_repellents");
   public static final TagKey PIGLIN_LOVED = of("piglin_loved");
   public static final TagKey IGNORED_BY_PIGLIN_BABIES = of("ignored_by_piglin_babies");
   public static final TagKey PIGLIN_FOOD = of("piglin_food");
   public static final TagKey FOX_FOOD = of("fox_food");
   public static final TagKey GOLD_ORES = of("gold_ores");
   public static final TagKey IRON_ORES = of("iron_ores");
   public static final TagKey DIAMOND_ORES = of("diamond_ores");
   public static final TagKey REDSTONE_ORES = of("redstone_ores");
   public static final TagKey LAPIS_ORES = of("lapis_ores");
   public static final TagKey COAL_ORES = of("coal_ores");
   public static final TagKey EMERALD_ORES = of("emerald_ores");
   public static final TagKey COPPER_ORES = of("copper_ores");
   public static final TagKey NON_FLAMMABLE_WOOD = of("non_flammable_wood");
   public static final TagKey SOUL_FIRE_BASE_BLOCKS = of("soul_fire_base_blocks");
   public static final TagKey CANDLES = of("candles");
   public static final TagKey DIRT = of("dirt");
   public static final TagKey TERRACOTTA = of("terracotta");
   public static final TagKey COMPLETES_FIND_TREE_TUTORIAL = of("completes_find_tree_tutorial");
   public static final TagKey BOATS = of("boats");
   public static final TagKey CHEST_BOATS = of("chest_boats");
   public static final TagKey FISHES = of("fishes");
   public static final TagKey SIGNS = of("signs");
   public static final TagKey MUSIC_DISCS = of("music_discs");
   public static final TagKey CREEPER_DROP_MUSIC_DISCS = of("creeper_drop_music_discs");
   public static final TagKey COALS = of("coals");
   public static final TagKey ARROWS = of("arrows");
   public static final TagKey LECTERN_BOOKS = of("lectern_books");
   public static final TagKey BOOKSHELF_BOOKS = of("bookshelf_books");
   public static final TagKey BEACON_PAYMENT_ITEMS = of("beacon_payment_items");
   public static final TagKey STONE_TOOL_MATERIALS = of("stone_tool_materials");
   public static final TagKey STONE_CRAFTING_MATERIALS = of("stone_crafting_materials");
   public static final TagKey FREEZE_IMMUNE_WEARABLES = of("freeze_immune_wearables");
   public static final TagKey AXOLOTL_TEMPT_ITEMS = of("axolotl_tempt_items");
   public static final TagKey DAMPENS_VIBRATIONS = of("dampens_vibrations");
   public static final TagKey CLUSTER_MAX_HARVESTABLES = of("cluster_max_harvestables");
   public static final TagKey COMPASSES = of("compasses");
   public static final TagKey HANGING_SIGNS = of("hanging_signs");
   public static final TagKey CREEPER_IGNITERS = of("creeper_igniters");
   public static final TagKey NOTEBLOCK_TOP_INSTRUMENTS = of("noteblock_top_instruments");
   public static final TagKey TRIMMABLE_ARMOR = of("trimmable_armor");
   public static final TagKey TRIM_MATERIALS = of("trim_materials");
   public static final TagKey TRIM_TEMPLATES = of("trim_templates");
   public static final TagKey SNIFFER_FOOD = of("sniffer_food");
   public static final TagKey DECORATED_POT_SHARDS = of("decorated_pot_shards");
   public static final TagKey SWORDS = of("swords");
   public static final TagKey AXES = of("axes");
   public static final TagKey HOES = of("hoes");
   public static final TagKey PICKAXES = of("pickaxes");
   public static final TagKey SHOVELS = of("shovels");
   public static final TagKey TOOLS = of("tools");
   public static final TagKey BREAKS_DECORATED_POTS = of("breaks_decorated_pots");

   private ItemTags() {
   }

   private static TagKey of(String id) {
      return TagKey.of(RegistryKeys.ITEM, new Identifier(id));
   }
}
