/*
 * Decompiled with CFR 0.2.2 (FabricMC 7c48b8c4).
 */
package net.minecraft.registry.tag;

import net.minecraft.item.Item;
import net.minecraft.registry.RegistryKeys;
import net.minecraft.registry.tag.TagKey;
import net.minecraft.util.Identifier;

public final class ItemTags {
    public static final TagKey<Item> WOOL = ItemTags.of("wool");
    public static final TagKey<Item> PLANKS = ItemTags.of("planks");
    public static final TagKey<Item> STONE_BRICKS = ItemTags.of("stone_bricks");
    public static final TagKey<Item> WOODEN_BUTTONS = ItemTags.of("wooden_buttons");
    public static final TagKey<Item> STONE_BUTTONS = ItemTags.of("stone_buttons");
    public static final TagKey<Item> BUTTONS = ItemTags.of("buttons");
    public static final TagKey<Item> WOOL_CARPETS = ItemTags.of("wool_carpets");
    public static final TagKey<Item> WOODEN_DOORS = ItemTags.of("wooden_doors");
    public static final TagKey<Item> WOODEN_STAIRS = ItemTags.of("wooden_stairs");
    public static final TagKey<Item> WOODEN_SLABS = ItemTags.of("wooden_slabs");
    public static final TagKey<Item> WOODEN_FENCES = ItemTags.of("wooden_fences");
    public static final TagKey<Item> FENCE_GATES = ItemTags.of("fence_gates");
    public static final TagKey<Item> WOODEN_PRESSURE_PLATES = ItemTags.of("wooden_pressure_plates");
    public static final TagKey<Item> WOODEN_TRAPDOORS = ItemTags.of("wooden_trapdoors");
    public static final TagKey<Item> DOORS = ItemTags.of("doors");
    public static final TagKey<Item> SAPLINGS = ItemTags.of("saplings");
    public static final TagKey<Item> LOGS_THAT_BURN = ItemTags.of("logs_that_burn");
    public static final TagKey<Item> LOGS = ItemTags.of("logs");
    public static final TagKey<Item> DARK_OAK_LOGS = ItemTags.of("dark_oak_logs");
    public static final TagKey<Item> OAK_LOGS = ItemTags.of("oak_logs");
    public static final TagKey<Item> BIRCH_LOGS = ItemTags.of("birch_logs");
    public static final TagKey<Item> ACACIA_LOGS = ItemTags.of("acacia_logs");
    public static final TagKey<Item> CHERRY_LOGS = ItemTags.of("cherry_logs");
    public static final TagKey<Item> JUNGLE_LOGS = ItemTags.of("jungle_logs");
    public static final TagKey<Item> SPRUCE_LOGS = ItemTags.of("spruce_logs");
    public static final TagKey<Item> MANGROVE_LOGS = ItemTags.of("mangrove_logs");
    public static final TagKey<Item> CRIMSON_STEMS = ItemTags.of("crimson_stems");
    public static final TagKey<Item> WARPED_STEMS = ItemTags.of("warped_stems");
    public static final TagKey<Item> BAMBOO_BLOCKS = ItemTags.of("bamboo_blocks");
    public static final TagKey<Item> WART_BLOCKS = ItemTags.of("wart_blocks");
    public static final TagKey<Item> BANNERS = ItemTags.of("banners");
    public static final TagKey<Item> SAND = ItemTags.of("sand");
    public static final TagKey<Item> SMELTS_TO_GLASS = ItemTags.of("smelts_to_glass");
    public static final TagKey<Item> STAIRS = ItemTags.of("stairs");
    public static final TagKey<Item> SLABS = ItemTags.of("slabs");
    public static final TagKey<Item> WALLS = ItemTags.of("walls");
    public static final TagKey<Item> ANVIL = ItemTags.of("anvil");
    public static final TagKey<Item> RAILS = ItemTags.of("rails");
    public static final TagKey<Item> LEAVES = ItemTags.of("leaves");
    public static final TagKey<Item> TRAPDOORS = ItemTags.of("trapdoors");
    public static final TagKey<Item> SMALL_FLOWERS = ItemTags.of("small_flowers");
    public static final TagKey<Item> BEDS = ItemTags.of("beds");
    public static final TagKey<Item> FENCES = ItemTags.of("fences");
    public static final TagKey<Item> TALL_FLOWERS = ItemTags.of("tall_flowers");
    public static final TagKey<Item> FLOWERS = ItemTags.of("flowers");
    public static final TagKey<Item> PIGLIN_REPELLENTS = ItemTags.of("piglin_repellents");
    public static final TagKey<Item> PIGLIN_LOVED = ItemTags.of("piglin_loved");
    public static final TagKey<Item> IGNORED_BY_PIGLIN_BABIES = ItemTags.of("ignored_by_piglin_babies");
    public static final TagKey<Item> MEAT = ItemTags.of("meat");
    public static final TagKey<Item> SNIFFER_FOOD = ItemTags.of("sniffer_food");
    public static final TagKey<Item> PIGLIN_FOOD = ItemTags.of("piglin_food");
    public static final TagKey<Item> FOX_FOOD = ItemTags.of("fox_food");
    public static final TagKey<Item> COW_FOOD = ItemTags.of("cow_food");
    public static final TagKey<Item> GOAT_FOOD = ItemTags.of("goat_food");
    public static final TagKey<Item> SHEEP_FOOD = ItemTags.of("sheep_food");
    public static final TagKey<Item> WOLF_FOOD = ItemTags.of("wolf_food");
    public static final TagKey<Item> CAT_FOOD = ItemTags.of("cat_food");
    public static final TagKey<Item> HORSE_FOOD = ItemTags.of("horse_food");
    public static final TagKey<Item> HORSE_TEMPT_ITEMS = ItemTags.of("horse_tempt_items");
    public static final TagKey<Item> CAMEL_FOOD = ItemTags.of("camel_food");
    public static final TagKey<Item> ARMADILLO_FOOD = ItemTags.of("armadillo_food");
    public static final TagKey<Item> BEE_FOOD = ItemTags.of("bee_food");
    public static final TagKey<Item> CHICKEN_FOOD = ItemTags.of("chicken_food");
    public static final TagKey<Item> FROG_FOOD = ItemTags.of("frog_food");
    public static final TagKey<Item> HOGLIN_FOOD = ItemTags.of("hoglin_food");
    public static final TagKey<Item> LLAMA_FOOD = ItemTags.of("llama_food");
    public static final TagKey<Item> LLAMA_TEMPT_ITEMS = ItemTags.of("llama_tempt_items");
    public static final TagKey<Item> OCELOT_FOOD = ItemTags.of("ocelot_food");
    public static final TagKey<Item> PANDA_FOOD = ItemTags.of("panda_food");
    public static final TagKey<Item> PIG_FOOD = ItemTags.of("pig_food");
    public static final TagKey<Item> RABBIT_FOOD = ItemTags.of("rabbit_food");
    public static final TagKey<Item> STRIDER_FOOD = ItemTags.of("strider_food");
    public static final TagKey<Item> STRIDER_TEMPT_ITEMS = ItemTags.of("strider_tempt_items");
    public static final TagKey<Item> TURTLE_FOOD = ItemTags.of("turtle_food");
    public static final TagKey<Item> PARROT_FOOD = ItemTags.of("parrot_food");
    public static final TagKey<Item> PARROT_POISONOUS_FOOD = ItemTags.of("parrot_poisonous_food");
    public static final TagKey<Item> AXOLOTL_FOOD = ItemTags.of("axolotl_food");
    public static final TagKey<Item> GOLD_ORES = ItemTags.of("gold_ores");
    public static final TagKey<Item> IRON_ORES = ItemTags.of("iron_ores");
    public static final TagKey<Item> DIAMOND_ORES = ItemTags.of("diamond_ores");
    public static final TagKey<Item> REDSTONE_ORES = ItemTags.of("redstone_ores");
    public static final TagKey<Item> LAPIS_ORES = ItemTags.of("lapis_ores");
    public static final TagKey<Item> COAL_ORES = ItemTags.of("coal_ores");
    public static final TagKey<Item> EMERALD_ORES = ItemTags.of("emerald_ores");
    public static final TagKey<Item> COPPER_ORES = ItemTags.of("copper_ores");
    public static final TagKey<Item> NON_FLAMMABLE_WOOD = ItemTags.of("non_flammable_wood");
    public static final TagKey<Item> SOUL_FIRE_BASE_BLOCKS = ItemTags.of("soul_fire_base_blocks");
    public static final TagKey<Item> CANDLES = ItemTags.of("candles");
    public static final TagKey<Item> DIRT = ItemTags.of("dirt");
    public static final TagKey<Item> TERRACOTTA = ItemTags.of("terracotta");
    public static final TagKey<Item> COMPLETES_FIND_TREE_TUTORIAL = ItemTags.of("completes_find_tree_tutorial");
    public static final TagKey<Item> BOATS = ItemTags.of("boats");
    public static final TagKey<Item> CHEST_BOATS = ItemTags.of("chest_boats");
    public static final TagKey<Item> FISHES = ItemTags.of("fishes");
    public static final TagKey<Item> SIGNS = ItemTags.of("signs");
    public static final TagKey<Item> CREEPER_DROP_MUSIC_DISCS = ItemTags.of("creeper_drop_music_discs");
    public static final TagKey<Item> COALS = ItemTags.of("coals");
    public static final TagKey<Item> ARROWS = ItemTags.of("arrows");
    public static final TagKey<Item> LECTERN_BOOKS = ItemTags.of("lectern_books");
    public static final TagKey<Item> BOOKSHELF_BOOKS = ItemTags.of("bookshelf_books");
    public static final TagKey<Item> BEACON_PAYMENT_ITEMS = ItemTags.of("beacon_payment_items");
    public static final TagKey<Item> STONE_TOOL_MATERIALS = ItemTags.of("stone_tool_materials");
    public static final TagKey<Item> STONE_CRAFTING_MATERIALS = ItemTags.of("stone_crafting_materials");
    public static final TagKey<Item> FREEZE_IMMUNE_WEARABLES = ItemTags.of("freeze_immune_wearables");
    public static final TagKey<Item> DAMPENS_VIBRATIONS = ItemTags.of("dampens_vibrations");
    public static final TagKey<Item> CLUSTER_MAX_HARVESTABLES = ItemTags.of("cluster_max_harvestables");
    public static final TagKey<Item> COMPASSES = ItemTags.of("compasses");
    public static final TagKey<Item> HANGING_SIGNS = ItemTags.of("hanging_signs");
    public static final TagKey<Item> CREEPER_IGNITERS = ItemTags.of("creeper_igniters");
    public static final TagKey<Item> NOTEBLOCK_TOP_INSTRUMENTS = ItemTags.of("noteblock_top_instruments");
    public static final TagKey<Item> FOOT_ARMOR = ItemTags.of("foot_armor");
    public static final TagKey<Item> LEG_ARMOR = ItemTags.of("leg_armor");
    public static final TagKey<Item> CHEST_ARMOR = ItemTags.of("chest_armor");
    public static final TagKey<Item> HEAD_ARMOR = ItemTags.of("head_armor");
    public static final TagKey<Item> SKULLS = ItemTags.of("skulls");
    public static final TagKey<Item> TRIMMABLE_ARMOR = ItemTags.of("trimmable_armor");
    public static final TagKey<Item> TRIM_MATERIALS = ItemTags.of("trim_materials");
    public static final TagKey<Item> TRIM_TEMPLATES = ItemTags.of("trim_templates");
    public static final TagKey<Item> DECORATED_POT_SHERDS = ItemTags.of("decorated_pot_sherds");
    public static final TagKey<Item> DECORATED_POT_INGREDIENTS = ItemTags.of("decorated_pot_ingredients");
    public static final TagKey<Item> SWORDS = ItemTags.of("swords");
    public static final TagKey<Item> AXES = ItemTags.of("axes");
    public static final TagKey<Item> HOES = ItemTags.of("hoes");
    public static final TagKey<Item> PICKAXES = ItemTags.of("pickaxes");
    public static final TagKey<Item> SHOVELS = ItemTags.of("shovels");
    public static final TagKey<Item> BREAKS_DECORATED_POTS = ItemTags.of("breaks_decorated_pots");
    public static final TagKey<Item> VILLAGER_PLANTABLE_SEEDS = ItemTags.of("villager_plantable_seeds");
    public static final TagKey<Item> DYEABLE = ItemTags.of("dyeable");
    public static final TagKey<Item> FOOT_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/foot_armor");
    public static final TagKey<Item> LEG_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/leg_armor");
    public static final TagKey<Item> CHEST_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/chest_armor");
    public static final TagKey<Item> HEAD_ARMOR_ENCHANTABLE = ItemTags.of("enchantable/head_armor");
    public static final TagKey<Item> ARMOR_ENCHANTABLE = ItemTags.of("enchantable/armor");
    public static final TagKey<Item> SWORD_ENCHANTABLE = ItemTags.of("enchantable/sword");
    public static final TagKey<Item> FIRE_ASPECT_ENCHANTABLE = ItemTags.of("enchantable/fire_aspect");
    public static final TagKey<Item> SHARP_WEAPON_ENCHANTABLE = ItemTags.of("enchantable/sharp_weapon");
    public static final TagKey<Item> WEAPON_ENCHANTABLE = ItemTags.of("enchantable/weapon");
    public static final TagKey<Item> MINING_ENCHANTABLE = ItemTags.of("enchantable/mining");
    public static final TagKey<Item> MINING_LOOT_ENCHANTABLE = ItemTags.of("enchantable/mining_loot");
    public static final TagKey<Item> FISHING_ENCHANTABLE = ItemTags.of("enchantable/fishing");
    public static final TagKey<Item> TRIDENT_ENCHANTABLE = ItemTags.of("enchantable/trident");
    public static final TagKey<Item> DURABILITY_ENCHANTABLE = ItemTags.of("enchantable/durability");
    public static final TagKey<Item> BOW_ENCHANTABLE = ItemTags.of("enchantable/bow");
    public static final TagKey<Item> EQUIPPABLE_ENCHANTABLE = ItemTags.of("enchantable/equippable");
    public static final TagKey<Item> CROSSBOW_ENCHANTABLE = ItemTags.of("enchantable/crossbow");
    public static final TagKey<Item> VANISHING_ENCHANTABLE = ItemTags.of("enchantable/vanishing");
    public static final TagKey<Item> MACE_ENCHANTABLE = ItemTags.of("enchantable/mace");

    private ItemTags() {
    }

    private static TagKey<Item> of(String id) {
        return TagKey.of(RegistryKeys.ITEM, Identifier.method_60656(id));
    }
}

