/*
 * Decompiled with CFR 0.2.2 (FabricMC 7c48b8c4).
 * 
 * Could not load the following classes:
 *  net.fabricmc.api.EnvType
 *  net.fabricmc.api.Environment
 */
package net.minecraft.client.render.entity.model;

import com.google.common.collect.ImmutableMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import net.fabricmc.api.EnvType;
import net.fabricmc.api.Environment;
import net.minecraft.block.WoodType;
import net.minecraft.client.model.Dilation;
import net.minecraft.client.model.TexturedModelData;
import net.minecraft.client.render.block.entity.BannerBlockEntityRenderer;
import net.minecraft.client.render.block.entity.BedBlockEntityRenderer;
import net.minecraft.client.render.block.entity.BellBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ChestBlockEntityRenderer;
import net.minecraft.client.render.block.entity.ConduitBlockEntityRenderer;
import net.minecraft.client.render.block.entity.DecoratedPotBlockEntityRenderer;
import net.minecraft.client.render.block.entity.HangingSignBlockEntityRenderer;
import net.minecraft.client.render.block.entity.SignBlockEntityRenderer;
import net.minecraft.client.render.entity.EndCrystalEntityRenderer;
import net.minecraft.client.render.entity.EnderDragonEntityRenderer;
import net.minecraft.client.render.entity.WitherSkullEntityRenderer;
import net.minecraft.client.render.entity.feature.TridentRiptideFeatureRenderer;
import net.minecraft.client.render.entity.model.AllayEntityModel;
import net.minecraft.client.render.entity.model.ArmadilloEntityModel;
import net.minecraft.client.render.entity.model.ArmorEntityModel;
import net.minecraft.client.render.entity.model.ArmorStandArmorEntityModel;
import net.minecraft.client.render.entity.model.ArmorStandEntityModel;
import net.minecraft.client.render.entity.model.AxolotlEntityModel;
import net.minecraft.client.render.entity.model.BatEntityModel;
import net.minecraft.client.render.entity.model.BeeEntityModel;
import net.minecraft.client.render.entity.model.BipedEntityModel;
import net.minecraft.client.render.entity.model.BlazeEntityModel;
import net.minecraft.client.render.entity.model.BoatEntityModel;
import net.minecraft.client.render.entity.model.BoggedEntityModel;
import net.minecraft.client.render.entity.model.BookModel;
import net.minecraft.client.render.entity.model.BreezeEntityModel;
import net.minecraft.client.render.entity.model.CamelEntityModel;
import net.minecraft.client.render.entity.model.ChestBoatEntityModel;
import net.minecraft.client.render.entity.model.ChestRaftEntityModel;
import net.minecraft.client.render.entity.model.ChickenEntityModel;
import net.minecraft.client.render.entity.model.CodEntityModel;
import net.minecraft.client.render.entity.model.CowEntityModel;
import net.minecraft.client.render.entity.model.CreeperEntityModel;
import net.minecraft.client.render.entity.model.DolphinEntityModel;
import net.minecraft.client.render.entity.model.DonkeyEntityModel;
import net.minecraft.client.render.entity.model.DragonHeadEntityModel;
import net.minecraft.client.render.entity.model.DrownedEntityModel;
import net.minecraft.client.render.entity.model.ElytraEntityModel;
import net.minecraft.client.render.entity.model.EndermanEntityModel;
import net.minecraft.client.render.entity.model.EndermiteEntityModel;
import net.minecraft.client.render.entity.model.EntityModelLayer;
import net.minecraft.client.render.entity.model.EntityModelLayers;
import net.minecraft.client.render.entity.model.EvokerFangsEntityModel;
import net.minecraft.client.render.entity.model.FoxEntityModel;
import net.minecraft.client.render.entity.model.FrogEntityModel;
import net.minecraft.client.render.entity.model.GhastEntityModel;
import net.minecraft.client.render.entity.model.GoatEntityModel;
import net.minecraft.client.render.entity.model.GuardianEntityModel;
import net.minecraft.client.render.entity.model.HoglinEntityModel;
import net.minecraft.client.render.entity.model.HorseEntityModel;
import net.minecraft.client.render.entity.model.IllagerEntityModel;
import net.minecraft.client.render.entity.model.IronGolemEntityModel;
import net.minecraft.client.render.entity.model.LargePufferfishEntityModel;
import net.minecraft.client.render.entity.model.LargeTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.LeashKnotEntityModel;
import net.minecraft.client.render.entity.model.LlamaEntityModel;
import net.minecraft.client.render.entity.model.LlamaSpitEntityModel;
import net.minecraft.client.render.entity.model.MagmaCubeEntityModel;
import net.minecraft.client.render.entity.model.MediumPufferfishEntityModel;
import net.minecraft.client.render.entity.model.MinecartEntityModel;
import net.minecraft.client.render.entity.model.OcelotEntityModel;
import net.minecraft.client.render.entity.model.PandaEntityModel;
import net.minecraft.client.render.entity.model.ParrotEntityModel;
import net.minecraft.client.render.entity.model.PhantomEntityModel;
import net.minecraft.client.render.entity.model.PigEntityModel;
import net.minecraft.client.render.entity.model.PiglinEntityModel;
import net.minecraft.client.render.entity.model.PiglinHeadEntityModel;
import net.minecraft.client.render.entity.model.PlayerEntityModel;
import net.minecraft.client.render.entity.model.PolarBearEntityModel;
import net.minecraft.client.render.entity.model.RabbitEntityModel;
import net.minecraft.client.render.entity.model.RaftEntityModel;
import net.minecraft.client.render.entity.model.RavagerEntityModel;
import net.minecraft.client.render.entity.model.SalmonEntityModel;
import net.minecraft.client.render.entity.model.SheepEntityModel;
import net.minecraft.client.render.entity.model.SheepWoolEntityModel;
import net.minecraft.client.render.entity.model.ShieldEntityModel;
import net.minecraft.client.render.entity.model.ShulkerBulletEntityModel;
import net.minecraft.client.render.entity.model.ShulkerEntityModel;
import net.minecraft.client.render.entity.model.SilverfishEntityModel;
import net.minecraft.client.render.entity.model.SkeletonEntityModel;
import net.minecraft.client.render.entity.model.SkullEntityModel;
import net.minecraft.client.render.entity.model.SlimeEntityModel;
import net.minecraft.client.render.entity.model.SmallPufferfishEntityModel;
import net.minecraft.client.render.entity.model.SmallTropicalFishEntityModel;
import net.minecraft.client.render.entity.model.SnifferEntityModel;
import net.minecraft.client.render.entity.model.SnowGolemEntityModel;
import net.minecraft.client.render.entity.model.SpiderEntityModel;
import net.minecraft.client.render.entity.model.SquidEntityModel;
import net.minecraft.client.render.entity.model.StriderEntityModel;
import net.minecraft.client.render.entity.model.TadpoleEntityModel;
import net.minecraft.client.render.entity.model.TridentEntityModel;
import net.minecraft.client.render.entity.model.TurtleEntityModel;
import net.minecraft.client.render.entity.model.VexEntityModel;
import net.minecraft.client.render.entity.model.VillagerResemblingModel;
import net.minecraft.client.render.entity.model.WardenEntityModel;
import net.minecraft.client.render.entity.model.WindChargeEntityModel;
import net.minecraft.client.render.entity.model.WitchEntityModel;
import net.minecraft.client.render.entity.model.WitherEntityModel;
import net.minecraft.client.render.entity.model.WolfEntityModel;
import net.minecraft.client.render.entity.model.ZombieVillagerEntityModel;
import net.minecraft.entity.vehicle.BoatEntity;

@Environment(value=EnvType.CLIENT)
public class EntityModels {
    private static final Dilation FISH_PATTERN_DILATION = new Dilation(0.008f);
    private static final Dilation ARMOR_DILATION = new Dilation(1.0f);
    private static final Dilation HAT_DILATION = new Dilation(0.5f);

    public static Map<EntityModelLayer, TexturedModelData> getModels() {
        ImmutableMap.Builder<EntityModelLayer, TexturedModelData> builder = ImmutableMap.builder();
        TexturedModelData lv = TexturedModelData.of(BipedEntityModel.getModelData(Dilation.NONE, 0.0f), 64, 64);
        TexturedModelData lv2 = TexturedModelData.of(ArmorEntityModel.getModelData(ARMOR_DILATION), 64, 32);
        TexturedModelData lv3 = TexturedModelData.of(ArmorEntityModel.getModelData(new Dilation(1.02f)), 64, 32);
        TexturedModelData lv4 = TexturedModelData.of(ArmorEntityModel.getModelData(HAT_DILATION), 64, 32);
        TexturedModelData lv5 = MinecartEntityModel.getTexturedModelData();
        TexturedModelData lv6 = SkullEntityModel.getSkullTexturedModelData();
        TexturedModelData lv7 = TexturedModelData.of(HorseEntityModel.getModelData(Dilation.NONE), 64, 64);
        TexturedModelData lv8 = IllagerEntityModel.getTexturedModelData();
        TexturedModelData lv9 = CowEntityModel.getTexturedModelData();
        TexturedModelData lv10 = TexturedModelData.of(OcelotEntityModel.getModelData(Dilation.NONE), 64, 32);
        TexturedModelData lv11 = TexturedModelData.of(PiglinEntityModel.getModelData(Dilation.NONE), 64, 64);
        TexturedModelData lv12 = TexturedModelData.of(PiglinHeadEntityModel.getModelData(), 64, 64);
        TexturedModelData lv13 = SkullEntityModel.getHeadTexturedModelData();
        TexturedModelData lv14 = LlamaEntityModel.getTexturedModelData(Dilation.NONE);
        TexturedModelData lv15 = StriderEntityModel.getTexturedModelData();
        TexturedModelData lv16 = HoglinEntityModel.getTexturedModelData();
        TexturedModelData lv17 = SkeletonEntityModel.getTexturedModelData();
        TexturedModelData lv18 = TexturedModelData.of(VillagerResemblingModel.getModelData(), 64, 64);
        TexturedModelData lv19 = SpiderEntityModel.getTexturedModelData();
        builder.put(EntityModelLayers.ALLAY, AllayEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ARMADILLO, ArmadilloEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ARMOR_STAND, ArmorStandEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ARMOR_STAND_INNER_ARMOR, ArmorStandArmorEntityModel.getTexturedModelData(HAT_DILATION));
        builder.put(EntityModelLayers.ARMOR_STAND_OUTER_ARMOR, ArmorStandArmorEntityModel.getTexturedModelData(ARMOR_DILATION));
        builder.put(EntityModelLayers.AXOLOTL, AxolotlEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BANNER, BannerBlockEntityRenderer.getTexturedModelData());
        builder.put(EntityModelLayers.BAT, BatEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BED_FOOT, BedBlockEntityRenderer.getFootTexturedModelData());
        builder.put(EntityModelLayers.BED_HEAD, BedBlockEntityRenderer.getHeadTexturedModelData());
        builder.put(EntityModelLayers.BEE, BeeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BELL, BellBlockEntityRenderer.getTexturedModelData());
        builder.put(EntityModelLayers.BLAZE, BlazeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BOGGED, BoggedEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.BOGGED_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.BOGGED_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.BOGGED_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.2f), 0.0f), 64, 32));
        builder.put(EntityModelLayers.BOOK, BookModel.getTexturedModelData());
        builder.put(EntityModelLayers.BREEZE, BreezeEntityModel.getTexturedModelData(32, 32));
        builder.put(EntityModelLayers.BREEZE_WIND, BreezeEntityModel.getTexturedModelData(128, 128));
        builder.put(EntityModelLayers.CAT, lv10);
        builder.put(EntityModelLayers.CAT_COLLAR, TexturedModelData.of(OcelotEntityModel.getModelData(new Dilation(0.01f)), 64, 32));
        builder.put(EntityModelLayers.CAMEL, CamelEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.CAVE_SPIDER, lv19);
        builder.put(EntityModelLayers.CHEST, ChestBlockEntityRenderer.getSingleTexturedModelData());
        builder.put(EntityModelLayers.CHEST_MINECART, lv5);
        builder.put(EntityModelLayers.CHICKEN, ChickenEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.COD, CodEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.COMMAND_BLOCK_MINECART, lv5);
        builder.put(EntityModelLayers.CONDUIT_EYE, ConduitBlockEntityRenderer.getEyeTexturedModelData());
        builder.put(EntityModelLayers.CONDUIT_WIND, ConduitBlockEntityRenderer.getWindTexturedModelData());
        builder.put(EntityModelLayers.CONDUIT_SHELL, ConduitBlockEntityRenderer.getShellTexturedModelData());
        builder.put(EntityModelLayers.CONDUIT, ConduitBlockEntityRenderer.getPlainTexturedModelData());
        builder.put(EntityModelLayers.COW, lv9);
        builder.put(EntityModelLayers.CREEPER, CreeperEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.CREEPER_ARMOR, CreeperEntityModel.getTexturedModelData(new Dilation(2.0f)));
        builder.put(EntityModelLayers.CREEPER_HEAD, lv6);
        builder.put(EntityModelLayers.DECORATED_POT_BASE, DecoratedPotBlockEntityRenderer.getTopBottomNeckTexturedModelData());
        builder.put(EntityModelLayers.DECORATED_POT_SIDES, DecoratedPotBlockEntityRenderer.getSidesTexturedModelData());
        builder.put(EntityModelLayers.DOLPHIN, DolphinEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.DONKEY, DonkeyEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.DOUBLE_CHEST_LEFT, ChestBlockEntityRenderer.getLeftDoubleTexturedModelData());
        builder.put(EntityModelLayers.DOUBLE_CHEST_RIGHT, ChestBlockEntityRenderer.getRightDoubleTexturedModelData());
        builder.put(EntityModelLayers.DRAGON_SKULL, DragonHeadEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.DROWNED, DrownedEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.DROWNED_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.DROWNED_OUTER_ARMOR, lv4);
        builder.put(EntityModelLayers.DROWNED_OUTER, DrownedEntityModel.getTexturedModelData(new Dilation(0.25f)));
        builder.put(EntityModelLayers.ELDER_GUARDIAN, GuardianEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ELYTRA, ElytraEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ENDERMAN, EndermanEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ENDERMITE, EndermiteEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ENDER_DRAGON, EnderDragonEntityRenderer.getTexturedModelData());
        builder.put(EntityModelLayers.END_CRYSTAL, EndCrystalEntityRenderer.getTexturedModelData());
        builder.put(EntityModelLayers.EVOKER, lv8);
        builder.put(EntityModelLayers.EVOKER_FANGS, EvokerFangsEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.FOX, FoxEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.FROG, FrogEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.FURNACE_MINECART, lv5);
        builder.put(EntityModelLayers.GHAST, GhastEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.GIANT, lv);
        builder.put(EntityModelLayers.GIANT_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.GIANT_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.GLOW_SQUID, SquidEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.GOAT, GoatEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.GUARDIAN, GuardianEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.HOGLIN, lv16);
        builder.put(EntityModelLayers.HOPPER_MINECART, lv5);
        builder.put(EntityModelLayers.HORSE, lv7);
        builder.put(EntityModelLayers.HORSE_ARMOR, TexturedModelData.of(HorseEntityModel.getModelData(new Dilation(0.1f)), 64, 64));
        builder.put(EntityModelLayers.HUSK, lv);
        builder.put(EntityModelLayers.HUSK_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.HUSK_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.ILLUSIONER, lv8);
        builder.put(EntityModelLayers.IRON_GOLEM, IronGolemEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.LEASH_KNOT, LeashKnotEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.LLAMA, lv14);
        builder.put(EntityModelLayers.LLAMA_DECOR, LlamaEntityModel.getTexturedModelData(new Dilation(0.5f)));
        builder.put(EntityModelLayers.LLAMA_SPIT, LlamaSpitEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.MAGMA_CUBE, MagmaCubeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.MINECART, lv5);
        builder.put(EntityModelLayers.MOOSHROOM, lv9);
        builder.put(EntityModelLayers.MULE, DonkeyEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.OCELOT, lv10);
        builder.put(EntityModelLayers.PANDA, PandaEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PARROT, ParrotEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PHANTOM, PhantomEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PIG, PigEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.PIG_SADDLE, PigEntityModel.getTexturedModelData(new Dilation(0.5f)));
        builder.put(EntityModelLayers.PIGLIN, lv11);
        builder.put(EntityModelLayers.PIGLIN_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PIGLIN_OUTER_ARMOR, lv3);
        builder.put(EntityModelLayers.PIGLIN_BRUTE, lv11);
        builder.put(EntityModelLayers.PIGLIN_BRUTE_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PIGLIN_BRUTE_OUTER_ARMOR, lv3);
        builder.put(EntityModelLayers.PIGLIN_HEAD, lv12);
        builder.put(EntityModelLayers.PILLAGER, lv8);
        builder.put(EntityModelLayers.PLAYER, TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, false), 64, 64));
        builder.put(EntityModelLayers.PLAYER_HEAD, lv13);
        builder.put(EntityModelLayers.PLAYER_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PLAYER_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.PLAYER_SLIM, TexturedModelData.of(PlayerEntityModel.getTexturedModelData(Dilation.NONE, true), 64, 64));
        builder.put(EntityModelLayers.PLAYER_SLIM_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.PLAYER_SLIM_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.SPIN_ATTACK, TridentRiptideFeatureRenderer.getTexturedModelData());
        builder.put(EntityModelLayers.POLAR_BEAR, PolarBearEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PUFFERFISH_BIG, LargePufferfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PUFFERFISH_MEDIUM, MediumPufferfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.PUFFERFISH_SMALL, SmallPufferfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.RABBIT, RabbitEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.RAVAGER, RavagerEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SALMON, SalmonEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHEEP, SheepEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHEEP_FUR, SheepWoolEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHIELD, ShieldEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHULKER, ShulkerEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SHULKER_BULLET, ShulkerBulletEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SILVERFISH, SilverfishEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SKELETON, lv17);
        builder.put(EntityModelLayers.SKELETON_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.SKELETON_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.SKELETON_HORSE, lv7);
        builder.put(EntityModelLayers.SKELETON_SKULL, lv6);
        builder.put(EntityModelLayers.SLIME, SlimeEntityModel.getInnerTexturedModelData());
        builder.put(EntityModelLayers.SLIME_OUTER, SlimeEntityModel.getOuterTexturedModelData());
        builder.put(EntityModelLayers.SNIFFER, SnifferEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SNOW_GOLEM, SnowGolemEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.SPAWNER_MINECART, lv5);
        builder.put(EntityModelLayers.SPIDER, lv19);
        builder.put(EntityModelLayers.SQUID, SquidEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.STRAY, lv17);
        builder.put(EntityModelLayers.STRAY_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.STRAY_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.STRAY_OUTER, TexturedModelData.of(BipedEntityModel.getModelData(new Dilation(0.25f), 0.0f), 64, 32));
        builder.put(EntityModelLayers.STRIDER, lv15);
        builder.put(EntityModelLayers.STRIDER_SADDLE, lv15);
        builder.put(EntityModelLayers.TADPOLE, TadpoleEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.TNT_MINECART, lv5);
        builder.put(EntityModelLayers.TRADER_LLAMA, lv14);
        builder.put(EntityModelLayers.TRIDENT, TridentEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.TROPICAL_FISH_LARGE, LargeTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.TROPICAL_FISH_LARGE_PATTERN, LargeTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
        builder.put(EntityModelLayers.TROPICAL_FISH_SMALL, SmallTropicalFishEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.TROPICAL_FISH_SMALL_PATTERN, SmallTropicalFishEntityModel.getTexturedModelData(FISH_PATTERN_DILATION));
        builder.put(EntityModelLayers.TURTLE, TurtleEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.VEX, VexEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.VILLAGER, lv18);
        builder.put(EntityModelLayers.VINDICATOR, lv8);
        builder.put(EntityModelLayers.WARDEN, WardenEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.WANDERING_TRADER, lv18);
        builder.put(EntityModelLayers.WIND_CHARGE, WindChargeEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.WITCH, WitchEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.WITHER, WitherEntityModel.getTexturedModelData(Dilation.NONE));
        builder.put(EntityModelLayers.WITHER_ARMOR, WitherEntityModel.getTexturedModelData(HAT_DILATION));
        builder.put(EntityModelLayers.WITHER_SKULL, WitherSkullEntityRenderer.getTexturedModelData());
        builder.put(EntityModelLayers.WITHER_SKELETON, lv17);
        builder.put(EntityModelLayers.WITHER_SKELETON_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.WITHER_SKELETON_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.WITHER_SKELETON_SKULL, lv6);
        builder.put(EntityModelLayers.WOLF, TexturedModelData.of(WolfEntityModel.getTexturedModelData(Dilation.NONE), 64, 32));
        builder.put(EntityModelLayers.WOLF_ARMOR, TexturedModelData.of(WolfEntityModel.getTexturedModelData(new Dilation(0.2f)), 64, 32));
        builder.put(EntityModelLayers.ZOGLIN, lv16);
        builder.put(EntityModelLayers.ZOMBIE, lv);
        builder.put(EntityModelLayers.ZOMBIE_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.ZOMBIE_OUTER_ARMOR, lv2);
        builder.put(EntityModelLayers.ZOMBIE_HEAD, lv13);
        builder.put(EntityModelLayers.ZOMBIE_HORSE, lv7);
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER, ZombieVillagerEntityModel.getTexturedModelData());
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_INNER_ARMOR, ZombieVillagerEntityModel.getArmorTexturedModelData(HAT_DILATION));
        builder.put(EntityModelLayers.ZOMBIE_VILLAGER_OUTER_ARMOR, ZombieVillagerEntityModel.getArmorTexturedModelData(ARMOR_DILATION));
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN, lv11);
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_INNER_ARMOR, lv4);
        builder.put(EntityModelLayers.ZOMBIFIED_PIGLIN_OUTER_ARMOR, lv3);
        TexturedModelData lv20 = BoatEntityModel.getTexturedModelData();
        TexturedModelData lv21 = ChestBoatEntityModel.getTexturedModelData();
        TexturedModelData lv22 = RaftEntityModel.getTexturedModelData();
        TexturedModelData lv23 = ChestRaftEntityModel.getTexturedModelData();
        for (BoatEntity.Type lv24 : BoatEntity.Type.values()) {
            if (lv24 == BoatEntity.Type.BAMBOO) {
                builder.put(EntityModelLayers.createBoat(lv24), lv22);
                builder.put(EntityModelLayers.createChestBoat(lv24), lv23);
                continue;
            }
            builder.put(EntityModelLayers.createBoat(lv24), lv20);
            builder.put(EntityModelLayers.createChestBoat(lv24), lv21);
        }
        TexturedModelData lv25 = SignBlockEntityRenderer.getTexturedModelData();
        WoodType.stream().forEach(signType -> builder.put(EntityModelLayers.createSign(signType), lv25));
        TexturedModelData lv26 = HangingSignBlockEntityRenderer.getTexturedModelData();
        WoodType.stream().forEach(signType -> builder.put(EntityModelLayers.createHangingSign(signType), lv26));
        ImmutableMap<EntityModelLayer, TexturedModelData> immutableMap = builder.build();
        List list = EntityModelLayers.getLayers().filter(layer -> !immutableMap.containsKey(layer)).collect(Collectors.toList());
        if (!list.isEmpty()) {
            throw new IllegalStateException("Missing layer definitions: " + String.valueOf(list));
        }
        return immutableMap;
    }
}

